empresas = [
    {"id": 1, "nombre": "Diego Antonio Ugaz Medina", "ruc": 10166550373},
    {"id": 2, "nombre": "Ugaz & Ugaz Ingenieros S.R.L.", "ruc": 20561275344},
    {
        "id": 3,
        "nombre": "Constructora & Consultora CEMAYU S.A.C.",
        "ruc": 20561215791,
    },
    {
        "id": 4,
        "nombre": "Constructora Tambo Real C & V Servicios Generales S.A.C.",
        "ruc": 20605788476,
    },
    {"id": 5, "nombre": "Sólida S.A.C.", "ruc": 20479606901},
    {"id": 6, "nombre": "Marco Erinson Gastulo Jiménez", "ruc": 10176172300},
    {"id": 7, "nombre": "Juan Carlos Pareja Arenas", "ruc": 10164881640},
    {
        "id": 8,
        "nombre": "Pacífico Ingenieros Asociados S.A.C.",
        "ruc": 20606190281,
    },
    {"id": 9, "nombre": "Construamérica E.I.R.L.", "ruc": 20508278790},
    {"id": 10, "nombre": "Corporación César's S.A.C.", "ruc": 20505410450},
    {"id": 11, "nombre": "Construcciones Royal E.I.R.L.", "ruc": 20510352328},
    {"id": 12, "nombre": "Tapia & Ugaz Ingenieros S.A.C.", "ruc": 20525563333},
    {
        "id": 13,
        "nombre": "Empresa Constructora Victoria S.A.",
        "ruc": 20495802401,
    },
    {"id": 14, "nombre": "Edilberto Tello Cabrera", "ruc": 10164611472},
    {"id": 15, "nombre": "Construcciones Alardi S.A.C.", "ruc": 20488147600},
    {
        "id": 17,
        "nombre": "Grupo Inversionista Boyer S.R.L.",
        "ruc": 20602643931,
    },
    {"id": 18, "nombre": "Construcciones EQQUS S.A.", "ruc": 20375458307},
    {"id": 19, "nombre": "Corporación Portilla S.A.C.", "ruc": 20487660991},
    {"id": 20, "nombre": "Julia Victoria Ugaz Medina", "ruc": 10167305577},
    {
        "id": 21,
        "nombre": "ENDICON Contratistas & Consultores E.I.R.L.",
        "ruc": 20487980634,
    },
    {
        "id": 22,
        "nombre": "Dávila y Acuña Contratistas Generales",
        "ruc": 20270375180,
    },
    {
        "id": 23,
        "nombre": "Consultores y Ejecutores Nimaos E.I.R.L.",
        "ruc": 20539016629,
    },
    {"id": 24, "nombre": "Bacilio Constructores S.A.C.", "ruc": 20479904082},
    {"id": 25, "nombre": "Arturo Burga Salazar", "ruc": 10166907271},
    {"id": 26, "nombre": "Kapo Constructores S.A.C.", "ruc": 20480708505},
    {
        "id": 27,
        "nombre": "CCN Consultorías Construcciones Nacionales y Servicios Generales",
        "ruc": 20561143511,
    },
    {"id": 28, "nombre": "Miguel Núñez Cotrina", "ruc": 10174425766},
    {
        "id": 29,
        "nombre": "San José Contratistas y Servicios Generales S.A.C.",
        "ruc": 20491617439,
    },
    {"id": 30, "nombre": "Construcciones M & F S.R.L.", "ruc": 20480577567},
    {"id": 31, "nombre": "Johnny Alan Ventura Carrillo", "ruc": 10423112099},
    {
        "id": 32,
        "nombre": "ABZ Consultores y Consultores S.A.C.",
        "ruc": 20561408671,
    },
    {"id": 33, "nombre": "Julio César Quiroz Ayasta", "ruc": 10267226933},
    {
        "id": 34,
        "nombre": "Corporación Zapata Ingenieros S.A.C.",
        "ruc": 20600835638,
    },
    {"id": 35, "nombre": "Corporacion Leo S.A.C.", "ruc": 20519615445},
    {
        "id": 36,
        "nombre": "F y M Ingeniería y Contratistas S.A.C.",
        "ruc": 20487943861,
    },
]

consorcios = [
    {"id": 1, "nombre": "Consorcio Cemayo"},
    {"id": 2, "nombre": "Consorcio Complejo Deportivo"},
    {"id": 3, "nombre": "Consorcio Constructor/POLIFAP"},
    {"id": 4, "nombre": "Consorcio Constructor/Máncora"},
    {"id": 5, "nombre": "Consorcio Cumbre III"},
    {"id": 6, "nombre": "Consorcio del Norte/El Imperial"},
    {"id": 7, "nombre": "Consorcio del Norte/Mochumí"},
    {"id": 8, "nombre": "Consorcio del Norte/MMUVALL"},
    {"id": 9, "nombre": "Consorcio del Norte/Tecapa"},
    {"id": 10, "nombre": "Consorcio del Norte/Lambayeque"},
    {"id": 11, "nombre": "Consorcio Dos"},
    {"id": 12, "nombre": "Consorcio Econvisa"},
    {"id": 13, "nombre": "Consorcio Edifica Perú"},
    {"id": 14, "nombre": "Consorcio Imperial"},
    {"id": 15, "nombre": "Consorcio Ingeniería/Seoane"},
    {"id": 16, "nombre": "Consorcio Ingeniería/Mochumí"},
    {"id": 17, "nombre": "Consorcio Ingenieros"},
    {"id": 18, "nombre": "Consorcio Jaén"},
    {"id": 19, "nombre": "Consorcio Jotoro"},
    {"id": 20, "nombre": "Consorcio La Mezcladora"},
    {"id": 21, "nombre": "Consorcio La Unión"},
    {"id": 22, "nombre": "Consorcio Nimaos"},
    {"id": 23, "nombre": "Consorcio Nueva Arica"},
    {"id": 24, "nombre": "Consorcio Ejecutor Salvador"},
    {"id": 25, "nombre": "Consorcio San Antonio"},
    {"id": 26, "nombre": "Consorcio San Carlos"},
    {"id": 27, "nombre": "Consorcio San José/Parque"},
    {"id": 28, "nombre": "Consorcio San José/La Pava"},
    {"id": 29, "nombre": "Consorcio San Juan Masías"},
    {"id": 30, "nombre": "Consorcio Santa Rosa/C-8"},
    {"id": 31, "nombre": "Consorcio Santa Rosa/Diego Ferré"},
    {"id": 32, "nombre": "Consorcio Tres"},
    {"id": 33, "nombre": "Consorcio Uno"},
    {"id": 34, "nombre": "Consorcio Vial Cúneo"},
    {"id": 35, "nombre": "Consorcio Vial Ingeniería/Huarmey"},
    {"id": 36, "nombre": "Consorcio Vial Ingeniería/Túcume"},
    {"id": 37, "nombre": "Consorcio Vial Ingeniería/Paita"},
    {"id": 38, "nombre": "Consorcio Vial Tarapoto"},
    {"id": 39, "nombre": "Consorcio Vial Valle Hermoso"},
    {"id": 40, "nombre": "Consorcio Victoria/Olmos"},
    {"id": 41, "nombre": "Consorcio Victoria/Mochumí"},
    {"id": 42, "nombre": "Consorcio Virgen de Fátima"},
]

entidades = [
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
    {"nombre": "__nombre__"},
]

consorcios_empresas_m2m = [
    {"id": 1, "consorcio_id": 1, "empresa_id": 3, "participación": 0.4},
    {"id": 2, "consorcio_id": 1, "empresa_id": 1, "participación": 0.6},
    {"id": 3, "consorcio_id": 2, "empresa_id": 4, "participación": 0.5},
    {"id": 4, "consorcio_id": 2, "empresa_id": 1, "participación": 0.5},
    {"id": 5, "consorcio_id": 4, "empresa_id": 1, "participación": 0.01},
    {"id": 6, "consorcio_id": 4, "empresa_id": 5, "participación": 0.78},
    {"id": 7, "consorcio_id": 4, "empresa_id": 6, "participación": 0.2},
    {"id": 8, "consorcio_id": 4, "empresa_id": 7, "participación": 0.01},
    {"id": 9, "consorcio_id": 3, "empresa_id": 6, "participación": 0.99},
    {"id": 10, "consorcio_id": 3, "empresa_id": 1, "participación": 0.01},
    {"id": 11, "consorcio_id": 5, "empresa_id": 8, "participación": 0.49},
    {"id": 12, "consorcio_id": 5, "empresa_id": 1, "participación": 0.51},
    {"id": 13, "consorcio_id": 9, "empresa_id": 9, "participación": 0.4},
    {"id": 14, "consorcio_id": 9, "empresa_id": 10, "participación": 0.1},
    {"id": 15, "consorcio_id": 9, "empresa_id": 1, "participación": 0.5},
    {"id": 16, "consorcio_id": 10, "empresa_id": 1, "participación": 0.5},
    {"id": 17, "consorcio_id": 10, "empresa_id": 10, "participación": 0.1},
    {"id": 18, "consorcio_id": 10, "empresa_id": 11, "participación": 0.4},
    {"id": 19, "consorcio_id": 6, "empresa_id": 12, "participación": 0.99},
    {"id": 20, "consorcio_id": 6, "empresa_id": 1, "participación": 0.01},
    {"id": 21, "consorcio_id": 7, "empresa_id": 1, "participación": 0.995},
    {"id": 22, "consorcio_id": 7, "empresa_id": 13, "participación": 0.005},
    {"id": 23, "consorcio_id": 8, "empresa_id": 1, "participación": 0.4906},
    {"id": 24, "consorcio_id": 8, "empresa_id": 12, "participación": 0.47},
    {"id": 25, "consorcio_id": 8, "empresa_id": 14, "participación": 0.0394},
    {"id": 26, "consorcio_id": 11, "empresa_id": 15, "participación": 0.4},
    {"id": 27, "consorcio_id": 11, "empresa_id": 1, "participación": 0.6},
    {"id": 28, "consorcio_id": 12, "empresa_id": 1, "participación": 0.75},
    {"id": 29, "consorcio_id": 12, "empresa_id": 13, "participación": 0.25},
    {"id": 30, "consorcio_id": 13, "empresa_id": 17, "participación": 0.1},
    {"id": 31, "consorcio_id": 13, "empresa_id": 18, "participación": 0.45},
    {"id": 32, "consorcio_id": 13, "empresa_id": 1, "participación": 0.45},
    {"id": 33, "consorcio_id": 14, "empresa_id": 19, "participación": 0.14},
    {"id": 34, "consorcio_id": 14, "empresa_id": 1, "participación": 0.86},
    {"id": 35, "consorcio_id": 16, "empresa_id": 1, "participación": 0.8975},
    {"id": 36, "consorcio_id": 16, "empresa_id": 2, "participación": 0.1025},
    {"id": 37, "consorcio_id": 15, "empresa_id": 20, "participación": 0.35},
    {"id": 38, "consorcio_id": 15, "empresa_id": 13, "participación": 0.35},
    {"id": 39, "consorcio_id": 15, "empresa_id": 1, "participación": 0.3},
    {"id": 40, "consorcio_id": 17, "empresa_id": 15, "participación": 0.6},
    {"id": 41, "consorcio_id": 17, "empresa_id": 1, "participación": 0.4},
    {"id": 42, "consorcio_id": 18, "empresa_id": 21, "participación": 0.2},
    {"id": 43, "consorcio_id": 18, "empresa_id": 1, "participación": 0.8},
    {"id": 44, "consorcio_id": 19, "empresa_id": 20, "participación": 0.95},
    {"id": 45, "consorcio_id": 19, "empresa_id": 1, "participación": 0.05},
    {"id": 46, "consorcio_id": 20, "empresa_id": 2, "participación": 0.4},
    {"id": 47, "consorcio_id": 20, "empresa_id": 1, "participación": 0.6},
    {"id": 48, "consorcio_id": 21, "empresa_id": 22, "participación": 0.5},
    {"id": 49, "consorcio_id": 21, "empresa_id": 1, "participación": 0.5},
    {"id": 50, "consorcio_id": 22, "empresa_id": 23, "participación": 0.2},
    {"id": 51, "consorcio_id": 22, "empresa_id": 1, "participación": 0.8},
    {"id": 52, "consorcio_id": 24, "empresa_id": 24, "participación": 0.18},
    {"id": 53, "consorcio_id": 24, "empresa_id": 1, "participación": 0.82},
    {"id": 54, "consorcio_id": 25, "empresa_id": 25, "participación": 0.5},
    {"id": 55, "consorcio_id": 25, "empresa_id": 13, "participación": 0.48},
    {"id": 56, "consorcio_id": 25, "empresa_id": 1, "participación": 0.02},
    {"id": 57, "consorcio_id": 26, "empresa_id": 26, "participación": 0.35},
    {"id": 58, "consorcio_id": 26, "empresa_id": 1, "participación": 0.65},
    {"id": 59, "consorcio_id": 27, "empresa_id": 27, "participación": 0.21},
    {"id": 60, "consorcio_id": 27, "empresa_id": 28, "participación": 0.2},
    {"id": 61, "consorcio_id": 27, "empresa_id": 1, "participación": 0.77},
    {"id": 62, "consorcio_id": 28, "empresa_id": 1, "participación": 0.5},
    {"id": 63, "consorcio_id": 28, "empresa_id": 29, "participación": 0.5},
    {"id": 64, "consorcio_id": 29, "empresa_id": 1, "participación": 0.2},
    {"id": 65, "consorcio_id": 29, "empresa_id": 19, "participación": 0.8},
    {"id": 66, "consorcio_id": 30, "empresa_id": 12, "participación": 0.95},
    {"id": 67, "consorcio_id": 30, "empresa_id": 1, "participación": 0.05},
    {"id": 68, "consorcio_id": 32, "empresa_id": 1, "participación": 0.5},
    {"id": 69, "consorcio_id": 32, "empresa_id": 30, "participación": 0.5},
    {"id": 70, "consorcio_id": 33, "empresa_id": 2, "participación": 0.4},
    {"id": 71, "consorcio_id": 33, "empresa_id": 1, "participación": 0.6},
    {"id": 72, "consorcio_id": 34, "empresa_id": 1, "participación": 0.68},
    {"id": 73, "consorcio_id": 34, "empresa_id": 31, "participación": 0.02},
    {"id": 74, "consorcio_id": 34, "empresa_id": 32, "participación": 0.3},
    {"id": 75, "consorcio_id": 35, "empresa_id": 15, "participación": 0.49},
    {"id": 76, "consorcio_id": 35, "empresa_id": 1, "participación": 0.51},
    {"id": 77, "consorcio_id": 36, "empresa_id": 15, "participación": 0.6},
    {"id": 78, "consorcio_id": 36, "empresa_id": 1, "participación": 0.4},
    {"id": 79, "consorcio_id": 37, "empresa_id": 15, "participación": 0.48},
    {"id": 80, "consorcio_id": 37, "empresa_id": 1, "participación": 0.49},
    {"id": 81, "consorcio_id": 37, "empresa_id": 33, "participación": 0.02},
    {"id": 82, "consorcio_id": 37, "empresa_id": 34, "participación": 0.01},
    {"id": 83, "consorcio_id": 38, "empresa_id": 35, "participación": 0.5},
    {"id": 84, "consorcio_id": 38, "empresa_id": 1, "participación": 0.5},
    {"id": 85, "consorcio_id": 39, "empresa_id": 1, "participación": 0.5},
    {"id": 86, "consorcio_id": 39, "empresa_id": 2, "participación": 0.35},
    {"id": 87, "consorcio_id": 39, "empresa_id": 32, "participación": 0.15},
    {"id": 88, "consorcio_id": 41, "empresa_id": 1, "participación": 0.9112},
    {"id": 89, "consorcio_id": 41, "empresa_id": 2, "participación": 0.0888},
    {"id": 90, "consorcio_id": 40, "empresa_id": 13, "participación": 0.95},
    {"id": 91, "consorcio_id": 40, "empresa_id": 1, "participación": 0.05},
    {"id": 92, "consorcio_id": 42, "empresa_id": 1, "participación": 0.66},
    {"id": 93, "consorcio_id": 42, "empresa_id": 36, "participación": 0.2},
    {"id": 94, "consorcio_id": 42, "empresa_id": 13, "participación": 0.14},
]

from sqlalchemy import create_engine, select
from sqlalchemy.orm import sessionmaker

from orm.model import Consorcio

engine = create_engine("sqlite:///data/database.db", echo=True)
ses = sessionmaker(bind=engine, autoflush=False, autocommit=False)


def main():
    with ses.begin() as session:
        stmt = select(Consorcio)
        result = session.execute(stmt)
        empresas = [empresa.as_dict() for empresa in result.scalars()]

        print(empresas)


if __name__ == "__main__":
    main()
